### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tripu** [w3c/pronunciation#1]
On [&ldquo;Spoken Pronunciation Task Force of the APA WG, &sect; Current Work&rdquo;](https://www.w3.org/WAI/APA/task-forces/pronunciation/#work), the link reading [&ldquo;See the wiki for current planning and draft documents&rdquo;](https://www.w3.org/WAI/APA/task-forces/pronunciation/wiki/) is broken.

**Comment by alia11y** [comment]
Here is the link for wiki: https://github.com/w3c/pronunciation/wiki
Michael- is it something that we need to update the click through URL on https://www.w3.org/WAI/APA/task-forces/pronunciation/wiki/ ?

**Comment by michael-n-cooper** [comment]
Roy is meant to update the link.

**Comment by ruoxiran** [comment]
Hi Irfan, the [wiki link](https://www.w3.org/WAI/APA/task-forces/pronunciation/wiki/ ) I created is intended as a meeting information page for the task force as it is in W3C website, such as creating the F2F meeting page. 
I noticed that you have updated a lot of content on the [github wiki](https://github.com/w3c/pronunciation/wiki), and we can continue to use this wiki. Thank you for your update. @alia11y @
