### ISSUE TITLE
Use Case: aria-details

### ISSUE THREAD

**Issue by AutoSponge** [w3c/pronunciation#10]
# Case

Existing attribute, [`aria-details`](https://www.w3.org/TR/wai-aria-1.1/#aria-details) could be used with some modification to its behavior when an ssml pattern is present. The example below is of SSML but could be another implementation (including one that supports external reference).

Issues:
- will require significant input from AT/TTS vendors

Example from https://quiet-collar.glitch.me/:

```html
<p>
  You say, <span aria-details="pecan1">pecan</span>.
  I say, <span aria-details="pecan2">pecan</span>.
</p>
<div>
  <speak>
    <phoneme id="pecan1" alphabet="ipa" ph="pɪˈkɑːn"></phoneme> 
    <phoneme id="pecan2" alphabet="ipa" ph="ˈpi.kæn"></phoneme>
  </speak>
</div>
```

**Comment by mhakkinen** [comment]
I believe this suggested use of aria-details is counter to the specification in ARIA 1.1, specifically in that aria-details points to an extended description of the element (in effect the evolution of the longdesc), and the description is visible to all users.  Screen readers would be providing their own UI mechanism to indicate presence and provide navigation to the description content.  In the publishing context, practice is emerging to provide a visual affordance when details are available (e.g., the details element).  If the intent is to use aria-details to provide direct cueing to AT or other TTS users, I can't see this approach working.

**Comment by AutoSponge** [comment]
Currently, the group has not widely considered pronunciation instructions to be visible to any users. In this example, nothing is displayed to the user. Only AT/ssml-aware technology would use it. However, I see your point. Even a `<ruby>` element in the details which would display leaves a lot to be desired for long structures of pronunciation instructions.
