### ISSUE TITLE
Is an ARIA attribute too restrictive?

### ISSUE THREAD

**Issue by LJWatson** [w3c/pronunciation#2]
If we create an ARIA attribute to handle pronunciation, it will restrict support to AT. I think there may be a use case for other non AT technologies (like voice assistants, Web Speech API apps etc.) though.

**Comment by AutoSponge** [comment]
@LJWatson I was told that was also the conclusion of the aria working group.

In addition to the `data-*`, `aria-*`, and RDFa/ld+json suggesions, the other idea I'd like to research is a pattern like the `<svg><use href="..."/></svg>` pattern but for `<speak>`. A way to globally define SSML instructions using an external resource. I think this could reduce the burden on implementors (especially for systems with multiple translations available), reduce the payload (download and parse) for user agents, and allow browser-adjacent technology or user settings to prioritize or ignore the resources at it sees fit. For example, an OS-level decision could ignore the external SSML resource if system audio was muted.

- [ARIA-SSML proposal](https://github.com/alia11y/SSMLinHTMLproposal)
- [LD+JSON "Speakable" proposal](https://github.com/schemaorg/schemaorg/issues/1389)
- [Google's BETA Speakable Document](https://developers.google.com/search/docs/data-types/speakable)

**Comment by AutoSponge** [comment]
I mocked up some examples with microdata here: https://quiet-collar.glitch.me/

**Comment by AutoSponge** [comment]
ARIA is no longer a part of our current proposals, closing for now.
