### ISSUE TITLE
User Scenario: News Reader

### ISSUE THREAD

**Issue by mhakkinen** [w3c/pronunciation#21]
A news service, which offers a variety of methods for users to consume their daily and hourly news updates wishes to ensure that names of individuals and geographic locations are pronounced correctly when presented by text to speech synthesis (TTS). For example:

- the news web site offers a TTS reader that allows users to hear the page read out loud
- the news service offers podcasts of daily news summaries generated by TTS
- the news site is designed to be accessible and support users of assistive technologies such as screen readers
- the daily news updates are available in spoken form via Google Assistant and Amazon Echo, utilizing content from the news site

**Comment by AutoSponge** [comment]
needed info adopted into docs
