### ISSUE TITLE
User Scenarios: Pronunciation of gender-neutral words

### ISSUE THREAD

**Issue by AutoSponge** [w3c/pronunciation#29]
From http://matatk.agrip.org.uk/articles/w3c-workshop-on-web-games/:

> Pronunciation of gender-neutral words
There was a session on diversity and localisation that included a talk about how translators might face barriers in using gender-neutral terms when translating into some languages, and how languages are evolving to create/allow for such terms. However, these emerging forms are not well-supported by text-to-speech systems.

The post continues and provides some examples. To sum up: language is constantly evolving as society evolves. We need tools that can keep up with these changes (re: accessibility). IMO, this is a great reason to support "author-specified" pronunciation in all areas of tech.

**Comment by alia11y** [comment]
Thank you for sharing. This is an excellent example and we can certainly add it into our use-cases.

**Comment by AutoSponge** [comment]
needed info adopted into docs
