### ISSUE TITLE
Reference JLreq and Simple Ruby

### ISSUE THREAD

**Issue by murata2makoto** [w3c/pronunciation#58]
Well-known [JLreq ](https://w3c.github.io/jlreq/) and a new document ["Rules for Simple Placement of Japanese Ruby"](https://www.w3.org/TR/2020/WD-simple-ruby-20200609/) should be referenced.

**Comment by AutoSponge** [comment]
Ruby no longer included as a implementation, will reopen if SSML in Ruby clarification is needed.
