### ISSUE TITLE
Do we really need "Goal" and "Target Audience" for every implementation approach in Section 3?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/pronunciation#59]
I do not think that each subsection of Section 3 needs subsections for goals and target audiences.  They should be described before Section 3.  Although some of the goals and audiences are outside the scope of a specific implementation approach, I think that "Problems and Limitations" subsections can describe them.

**Comment by AutoSponge** [comment]
explainer document will have more succinct sections.
