### ISSUE TITLE
Technical approach document editorial changes 

### ISSUE THREAD

**Issue by alia11y** [w3c/pronunciation#76]
As per Michael's feedback on the document review:

- I'm looking for, somewhere in the intro and possibly this para, a clear indication that there are two approaches being considered, but that at this point neither are explicitly on path to Recommendation, we actively want feedback on them in order to choose. I think this is more than a paragraph.

follow matrix with call to action requesting comments. to help move one of these approaches to technical recommendation. feedback from implementors and authors. (can or can't implement)

- The section "Background on Pronunciation" has only three sentences. That is not enough to justify a section. I think the section is needed, so it should have more content. While there are links, it would be important to summarize the content of the links so a reader can a) be introduced without having to follow links and b) understand why they might want to follow those links for more detail.

hanger and a list here. TLDR each doc.

- There should be a pros / cons section, either one in each approach, or a section following them comparing them and giving pros and cons as we understand them.

borrow heavily from previous documents (explainer)

**Comment by AutoSponge** [comment]
I've made changes to the intro (first pass) attempting to address these concerns. I've also split the approaches into a hanger and list format to make it more clear there are two. I've mentioned the call-to-action in the intro and again after the list of approaches. Feedback about the changes can be added here. I'll track this issue and assign myself.

**Comment by alia11y** [comment]
I have added background Information in the document.

**Comment by AutoSponge** [comment]
doc updated
