### ISSUE TITLE
CSS speech

### ISSUE THREAD

**Issue by minorninth** [w3c/pronunciation#90]
I'd love to know more about why CSS Speech / Aural CSS never went anywhere, and how we can ensure this proposal won't suffer the same fate.

CSS speech still seems to be getting regular updates: https://www.w3.org/TR/css-speech-1/

Is this meant to completely replace it?

**Comment by danielweck** [comment]
Hello, note that I am incorrectly listed as the current specification editor (people contacted me privately about the status of CSS Speech, so I thought I'd clarify this here :)

I believe @LJWatson is involved now.

See:
https://lists.w3.org/Archives/Public/www-style/2021Jun/0012.html

**Comment by AutoSponge** [comment]
Based on our [gap analysis document](https://www.w3.org/TR/pronunciation-gap-analysis-and-use-cases/#gap-analysis), CSS speech has no mechanism for language, phonetic pronunciation, substitution, and "say as" (feature).
